### PR TITLE
Move sketch to appropriately named subfolder

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires that a sketch be located in a folder of the same name. Although the name of the repository does match the sketch name, when GitHub's popular **Clone or download > Download ZIP** feature is used to download a repository the branch/release/commit name is appended to the folder name, causing a mismatch.

When opening a file that does not meet this sketch/folder name matching requirement the Arduino IDE presents a dialog:
```
The file "esp8266-fastled-webserver.ino" needs to be inside a sketch folder named "esp8266-fastled-webserver".
Create this folder, move the file, and continue?
```
After clicking "OK" the Arduino IDE currently moves only the file esp8266-fastled-webserver.ino to the new folder, leaving behind the other source files. This causes compilation of the sketch to fail:
```
esp8266-fastled-webserver-master\esp8266-fastled-webserver\esp8266-fastled-webserver.ino:34:30: fatal error: GradientPalettes.h: No such file or directory

 #include "GradientPalettes.h"
```

### CODE REVIEW

**Comment by per1234** [comment]
@jasoncoon why did you close this? The problem still exists.

**Comment by jasoncoon** [comment]
I closed this issue because I won't be "fixing" it.  You can either:

* use git to clone the repo, in which case it'll clone it to a folder named `esp8266-fastled-webserver`, and this problem won't exist, or
* use the download button to download the zip file, extract it to a folder named `esp8266-fastled-webserver`, and this problem won't exists, or
* etc

**Comment by per1234** [comment]
OK, well it's common courtesy and best practices to take a minute to write a short summary of the reasoning when closing a PR or issue.

**Comment by jasoncoon** [comment]
Ah, sorry, got mixed up.  I didn't actually close this pull request.  It got closed automatically when I renamed the default branch from `master` to `main` a bit ago.

But, that aside, sorry, I'm not planning on merging this PR.

**Comment by per1234** [comment]
Thanks for the clarification. I understand what happened now.

**Pull request closed without merging**
