### PR TITLE
#1 Refactored code and added mqtt support

### PR DESCRIPTION
**Pull request by awilhelmer**
Refactored code to use a MQTT Broker. All commands are only usable via MQTT. Deleted WebServer and IR Controller with the reason, that my stability was bad (lagging and flickering LED's in animations) with running WebServer.

### CODE REVIEW

**Comment by seanspotatobusiness** [comment]
If it no longer uses the webserver,  what is the user interface to control the LEDs? Sorry if that's a stupid question but I'm a noob. Is it basically command line operated in MQTT form?

**Comment by awilhelmer** [comment]
The best way to integrate my work is to use a separate MQTT branch. I removed the WebServer because i get problems with the protocol timings causing it to flickering LED's when a HTTP request is calculated.
You can control your LED's with any client you want. For example you can use a smartphone app (in my case i use "MQTT Dashboard" in Android, here you can define the control publish message like select a color etc.). My next step is to integrate these MQTT commands with an Alexa Skill (Amazon Echo).

**Comment by awilhelmer** [comment]
The general answer: MQTT is a topic based protocol. Imagine a server (in internet or in your local network). This system is a "broker". Your IoT devices listen for messages (or they periodically publish messages like the actual temperature), the broker delegate the messages on every subscriber on a specific topic name. With this infrastructure you are able to control 100 NodeMCU's with one client. The other advantage is security. You can host your broker in the internet with auth and SSL. You can control your devices over the internet without opening any port in your home network.

**Comment by seanspotatobusiness** [comment]
Okay, so you need another device to be switched on as a server for this to work? What device are you using for that?

Have you finished setting up the MQTT Dashboard and is possible to share the MQTT Dashboard files?

**Comment by awilhelmer** [comment]
The smartphone app is easy to use. Just configure your MQTT broker and add a "Switch" Component. Publish value on: power:1 
and off: 
power:0 
Enter the topic name where the NodeMCU subscribes on (These topics are automatically build on first use)
Read the README for all commands

**Comment by jasoncoon** [comment]
This looks interesting, and I hope to check out MQTT some time soon, but I'm not planning on merging this pull request.  The web server and IR control work great for me and many others.  Thanks for sharing, though!

**Comment by awilhelmer** [comment]
No prob. I made a rename on the forked repo so everbody have a choice. 
Thanks for you great work on this project!
https://github.com/awilhelmer/esp8266-fastled-mqtt

**Pull request closed without merging**
